#include <map>
#include <string>

enum ItemType {
    BALL_OF_YARN,
    COIN,
    PENCIL,
    SPORTS_SOCK,
    OTHER_SPORTS_SOCK,
    GLASS_OF_WATER,
    HYDROGEN_PEROXIDE,
    APPLE,
    KEYS,
    SCREWDRIVER,
    PIKMI_STICK,
    SECOND_SOCK,
    NEW_LIGHT_BULB,
    PHONE,
    STOOL,
    BATHTUB,
    LAUNDRY_BASKET,
    CAT,
    NOTE,
    BED,
    NIGHTSTAND,
    WARDROBE,
    TRASH_BIN,
    SOFA,
    CLOTHESLINE,
    KITCHEN_TABLE,
    SINK
};

static const std::map<ItemType, std::string> items = {
    {BALL_OF_YARN, "Ball of yarn"},
    {COIN, "Coin"},
    {PENCIL, "Pencil"},
    {SPORTS_SOCK, "Sports sock"},
    {OTHER_SPORTS_SOCK, "Other sports sock"},
    {GLASS_OF_WATER, "Glass of water"},
    {HYDROGEN_PEROXIDE, "Hydrogen peroxide"},
    {APPLE, "Apple"},
    {KEYS, "Keys"},
    {SCREWDRIVER, "Screwdriver"},
    {PIKMI_STICK, "Pikmi stick"},
    {SECOND_SOCK, "Second sock"},
    {NEW_LIGHT_BULB, "New light bulb"},
    {PHONE, "Phone"},
    {STOOL, "Stool"},
    {BATHTUB, "Bathtub"},
    {LAUNDRY_BASKET, "Laundry basket"},
    {CAT, "Cat"},
    {NOTE, "Note"},
    {BED, "Bed"},
    {NIGHTSTAND, "Nightstand"},
    {WARDROBE, "Wardrobe"},
    {TRASH_BIN, "Trash bin"},
    {SOFA, "Sofa"},
    {CLOTHESLINE, "Clothesline"},
    {KITCHEN_TABLE, "Kitchen table"},
    {SINK, "Sink"}
};